[tool.poetry]
name = "the-math-guys-bot"
version = "0.1.0"
description = ""
authors = ["MathItYT <benjamin.ubilla@uc.cl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
discord-py = "^2.3.2"
python-dotenv = "^1.0.0"
pandas = "^2.1.4"
sympy = "^1.12"
matplotlib = "^3.8.2"
antlr4-python3-runtime = "4.11"
google-generativeai = "^0.3.2"
mysqlclient = "^2.2.1"


[tool.poetry.group.dev.dependencies]
selenium = "^4.16.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
