[tool.poetry]
name = "the-math-guys-bot"
version = "0.1.0"
description = ""
authors = ["MathItYT <benjamin.ubilla@uc.cl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
python-dotenv = "^1.0.0"
pandas = "^2.1.4"
sympy = "^1.12"
matplotlib = "^3.8.2"
antlr4-python3-runtime = "4.11"
google-generativeai = "^0.3.2"
mysqlclient = "^2.2.1"
py-cord = {git = "https://github.com/Pycord-Development/pycord.git", branch="master", extras=["voice"]}
google-cloud-texttospeech = "^2.15.1"
google-cloud-speech = "^2.23.0"
google-cloud-storage = "^2.14.0"


[tool.poetry.group.dev.dependencies]
selenium = "^4.16.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
