[tool.poetry]
name = "the-math-guys-bot"
version = "0.1.0"
description = ""
authors = ["MathItYT <benjamin.ubilla@uc.cl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
python-dotenv = "^1.0.0"
sympy = "^1.12"
matplotlib = "^3.8.2"
py-cord = {git = "https://github.com/Pycord-Development/pycord.git", branch="master"}
google-generativeai = "^0.5.2"
antlr4-python3-runtime = "4.11"
restrictedpython = "^7.1"


[tool.poetry.group.dev.dependencies]
selenium = "^4.16.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
